# Document:
# http://simiki.org/docs/configuration.html

url: 
title: 
keywords: 
description: 
author:

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple2 
